### ISSUE TITLE
getSalesforceInstanceUrl doesn't work when opened a managed VF page

### ISSUE THREAD

**Issue by espl-saket** [saket-joshi/SFDC-Records-Copy#1]
Use the site - https://rc-event.na30.visual.force.com/apex/Campaign_Manage?scontrolCaching=1&id=701360000005CqJ

**Comment by saket-joshi** [comment]
- Tested for the following sample URLs
  - https://na30.salesforce.com/home/home.jsp
  - https://mycustomdomain-dev-ed--erd.ap1.visual.force.com/apex/VF_Page?sfdc.tabName=01r90000000hDtn
  - https://name-space.cs26.visual.force.com/apex/VF_Page?scontrolCaching=1&id=701210000005PO2
  - https://cs26.salesforce.com/home/home.jsp?sdtd=1
- Resolved in branch: issues/1
- Pull request created: #4

**Comment by saket-joshi** [comment]
Merged to master
