### ISSUE TITLE
Record IDs will be fetched along with other information in the URL

### ISSUE THREAD

**Issue by espl-saket** [saket-joshi/SFDC-Records-Copy#2]
Running the getSalesforceRecordId method would return the other parts of the URL as well. For instance, https://na30.salesforce.com/70136000000Ajp4AAC#70136000000Ajp4_RelatedCampaignHierarchyList_target would return 70136000000Ajp4AAC#70136000000Ajp4_RelatedCampaignHierarchyList_target
Which is not the correct URL

**Comment by saket-joshi** [comment]
- Tested for the following URLs
  - https://na30.salesforce.com/0033600000Kfouu
  - https://cs26.salesforce.com/701210000005PO2#701210000005PO2_RelatedCampaignMemberList_target
- Resolved in branch issue/2
- Pull request created #5

**Comment by saket-joshi** [comment]
Merged to master
